apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: dev
spec:
  type: NodePort
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30306
  selector:
    app: mysql